apiVersion: batch/v1
kind: Job
metadata:
  name: start-redis-cluster
spec:
  template:
    metadata:
      name: start-redis-cluster
    spec:
      containers:
      - name: redis-cli
        image: docker.io/redis:latest
        imagePullPolicy: IfNotPresent
        command:
        - redis-cli
        - --cluster
        - create
        - redis-cluster-0.redis:7777
        - redis-cluster-1.redis:7777
        - redis-cluster-2.redis:7777
        - --cluster-replicas
        - "0"
        - --cluster-yes
      restartPolicy: Never